destination: ./_site
markdown: kramdown
permalink: pretty
highlighter: rouge
archive_path: /archive
categories_path : /categories
tags_path : /tags
exclude:
  - readme.markdown
  - resume
  - Gemfile
  - vendor
  - .travis.yml
sass:
  style: :compressed
title: Rémy Léone
tagline: "Remy Leone's website"
url: "https://sieben.fr"
enforce_ssl: www.sieben.fr   # without any protocol
description: 'Cloud Developer Evangelist'
social_networks:
    - name: github
      url: https://github.com/remyleone
      logo: github
    - name: twitter
      url: https://www.twitter.com/remyleone
      logo: twitter
    - name: linkedin
      url: https://www.linkedin.com/in/remyleone
      logo: linkedin
    - name: google-scholar
      url: https://scholar.google.fr/citations?user=by3UkrwAAAAJ
      logo: book

github:
    repo: https://github.com/remyleone/remyleone.github.io

gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji
