destination: ./_site
markdown: kramdown
permalink: pretty
highlighter: pygments
archive_path: /archive
categories_path : /categories
tags_path : /tags
exclude: ["readme.markdown"]
sass:
  style: :compressed
title: Rémy Léone
tagline: "Remy Leone's website"
url: "http://sieben.fr"
description: 'PhD student working in the field of Wireless Sensor Networks'
social_networks:
    - name: github
      url: https://github.com/sieben
      logo: github
    - name: twitter
      url: https://www.twitter.com/remyleone
      logo: twitter
    - name: linkedin
      url: http://fr.linkedin.com/in/remyleone
      logo: linkedin
    - name: google-scholar
      url: http://scholar.google.fr/citations?user=by3UkrwAAAAJ
      logo: book

github:
    repo: https://github.com/sieben/sieben.github.com

gems:
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
